### ISSUE TITLE
reorder_within and two faceting variables? 

### ISSUE THREAD

**Issue by ARTKB** [dgrtwo/drlib#2]
Hi David, 

Thanks for these, they are great. 

I am trying to use reorder_within with facet_grid with two faceting variables. Now it seems like it was not designed for this and I was trying to update the functions to fit. It's easy enough with reorder_within but I cannot quite figure out how to do it with scale_x_reordered(). 

Example below of why scale_x_reorder needs to be rejigged for it, but I haven't a clue where to start. Any help definitely appreciated. 

``` r
library(tidyverse)
library(drlib)
#> 
#> Attaching package: 'drlib'
#> The following object is masked from 'package:tidyr':
#> 
#>     expand_grid
library(datasets)
data(iris)
df<-iris%>%
  gather(Type, value, -Species)%>%
  separate(Type, c("type", "attribute"), sep="[.]")


#using jsut reorder_within to test that it works
df%>%
  ggplot(aes(reorder_within(Species, value, type), value, color=type))+
  geom_point()+
  facet_grid(.~type, scales = "free_x")+
  scale_x_reordered()
```

![](https://i.imgur.com/YFGBc8e.png)

``` r


#creating a new reorder that would work with 2 varaibles
reorder_within_2 <- function(x, by, within, within1, fun = mean, sep = "___", ...) {
  new_x <- paste(x, within, within1, sep = sep)
  stats::reorder(new_x, by, FUN = fun)
}

#but now, creating the chart below, the species names repeat. 

df%>%
  ggplot(aes(reorder_within_2(Species, value, type, attribute), value, color=type))+
  geom_point()+
  facet_grid(attribute~type, scales = "free_x")+
  scale_x_reordered()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

![](https://i.imgur.com/mipSY63.png)

<sup>Created on 2020-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dgrtwo** [comment]
The issue here is that you can't have free scales for each plot in `facet_grid` (notice that even though you used `"free_x"` the x-axis is shared between the vertical pairs of plots).

Your two choices are to reorder only by attribute, or to use `facet_wrap(attribute ~ type)` instead:

```
df%>%
  ggplot(aes(reorder_within(Species, value, paste(type, attribute)), value, color=type))+
  geom_point()+
  facet_wrap(attribute~type, scales = "free_x")+
  scale_x_reordered()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

![image](https://user-images.githubusercontent.com/994718/73204964-fdffc700-410d-11ea-8952-e2006dfaaa98.png)

By the way, `reorder_within` now lives within the tidytext package (which is helpfully on CRAN!)

**Comment by ARTKB** [comment]
Thanks David!
